[package]
name = "subtui"
version = "0.1.0"
edition = "2024"
authors = [ "alemi <me@alemi.dev>" ]
description = "subsonic client, music player in your terminal"
license = "GPL-3.0"
keywords = ["cli", "tui", "audio", "subsonic", "music"]
repository = "https://github.com/alemidev/subtui"
readme = "README.md"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
cpal = "0.17"
dashmap = "6.1"
log = "0.4"
mpris-server = "0.9"
tokio = { version = "1.48", features = ["sync", "rt", "time", "macros"] }
rand = "0.9"
ratatui = "0.30"
rmp3 = { version = "0.3", features = ["float"] }
thiserror = "2.0"
notify-rust = { version = "4.11", features = ["image"] }
submarine = { version = "0.1", features = ["navidrome"] }

serde = { version = "1.0", features = ["derive"] }
serde-inline-default = "1.0"
serde_default = "0.2"
toml = "0.9"
